name: Format Terraform files

on:
  pull_request:
    paths:
      - '**/*.tf'

jobs:
  format:
    runs-on: ubuntu-latest
    name: Check terraform file are formatted correctly
    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.2

      - name: terraform fmt
        uses: dflook/terraform-fmt@v1
        with:
          path: ./

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v7
        with:
          commit-message: terraform fmt
          title: Reformat terraform files
          body: Update terraform files to canonical format using `terraform fmt`
          branch: automated-terraform-fmt
          delete-branch: true
