name: Automation

on: 
  pull_request:

jobs:
  automation-workflow:
    # uses: iits-consulting/terraform-opentelekomcloud-common-workflows/.github/workflows/workflow-reusable.yaml@main
    uses: .github/workflows/workflow-reusable.yaml@main


